### ISSUE TITLE
Incompatible handling of strings

### ISSUE THREAD

**Issue by tstewart-klaudhaus** [popeindustries/lit-html-server#125]
In `lit-html` the parameter to `render` can be a string. This is not the case in `lit-html-server`.

To reproduce:

```js
import { renderToString } from "@popeindustries/lit-html-server"
const result = await renderToString("test string")
```

Expected result to be equal to "test string".

Actual result is an error:

Error: unknown chunk type: test string

**Comment by popeindustries** [comment]
Yes, this was a feature recently added to `lit-html`. Should be relatively easy to add here. I'll see what I can do

**Comment by popeindustries** [comment]
https://github.com/popeindustries/lit-html-server/releases/tag/3.1.0

**Comment by tstewart-klaudhaus** [comment]
Thank you, works well.
