### ISSUE TITLE
lit-html-server and @lit-labs/ssr

### ISSUE THREAD

**Issue by GHNewbiee** [popeindustries/lit-html-server#137]
Hi, please let me know your thoughts about @lit-labs/ssr? What is the relative position of both projects? *Tia*

**Comment by popeindustries** [comment]
I had hoped to be able to retire this project once an official server renderer became available, but after some initial testing, it appears that @lit-labs/ssr is quite a lot slower (~14x) than this approach, even without the vm context isolation they are recommending (which must be even slower). Rendering performance is very important for my needs, while server rendering shadow DOM is not, so I will be working on a new version that can generate hydration metadata compatible with the upcoming lit-html@2.

**Comment by popeindustries** [comment]
Finally ready: [popeindustries/lit](https://github.com/popeindustries/lit)
