### ISSUE TITLE
Would love an example folder in the project

### ISSUE THREAD

**Issue by greg-benner-klick-sensei** [popeindustries/lit-html-server#4]
Sorry to be a noob I tried the docs but couldnt get it working, would be awesome to have the example in the project. `/examples`

**Comment by popeindustries** [comment]
Sorry about that - it's high on the todo list, but have been busy rewriting things! There is a [test file](https://github.com/popeindustries/lit-html-server/blob/master/test/server.js) that renders a dummy template for performance testing. Maybe that can help you get started?

**Comment by greg-benner-klick-sensei** [comment]
Yes, perfect for me. Thank you!
