### ISSUE TITLE
Type Declarations like lit-html?

### ISSUE THREAD

**Issue by Grunet** [popeindustries/lit-html-server#41]
Is there any way to use lit-html-server in typescript and benefit from the intellisense, type checking, etc... that the typescript compiler can provide? It looks like the core lit-html project emits declaration files, but the source is already in typescript there.

I tried converting all of the lit-html-server source to typescript using the js-to-ts-converter package and was able to clean up most of the resulting compile errors without much understanding of what the code was doing around it, but there were a couple I wasn't so sure how to handle.

**Comment by popeindustries** [comment]
It’s unfortunate that TypeScript projects don’t understand importing JS libraries using TSDocs. Creating *.d.ts files should just be copying the TSDocs from the existing source. I think @AndersCan was working on this?

**Comment by Grunet** [comment]
I found a solution from #https://github.com/microsoft/TypeScript/issues/29056 by setting allowJS to true and maxNodeModuleJsDepth to 5 in my tsconfig, which seems to pull in the JSDocs correctly. It looks like that's just a workaround for #https://github.com/microsoft/TypeScript/issues/7546 though.

The one build error I'm getting with that now in my starter project is that the "html" function seems to be expecting a string array instead of a TemplateStringsArray. 

![image](https://user-images.githubusercontent.com/29322882/60782894-f47d2600-a10d-11e9-9140-9c50f0de8cc2.png)

It looks like the core lit-html project has this typed as a TemplateStringsArray, so maybe the doc just needs updating?

![image](https://user-images.githubusercontent.com/29322882/60782958-29897880-a10e-11e9-9072-e4a4b329cb34.png)

![image](https://user-images.githubusercontent.com/29322882/60782980-3a39ee80-a10e-11e9-8d5d-2180a30244a7.png)

Not a big deal of course since I can just turn off the type checking for it
