### ISSUE TITLE
renderToStream using browser ReadableStream

### ISSUE THREAD

**Issue by robwebdev** [popeindustries/lit-html-server#7]
I noticed a TODO for this in the source and wanted to open an issue to give it some encouragement as I think it would be a great addition.

I'm currently experimenting with [trisomorphic](https://developers.google.com/web/updates/2019/02/rendering-on-the-web#trisomorphic) rendering and this would be a very interesting to me.

**Comment by popeindustries** [comment]
Yes! I think it would be cool too, and shouldn’t be too difficult to implement (in theory). I haven’t been doing any ServiceWorker stuff in a while, so it hasn’t been on the top of my list, but if you want to help out with some testing, I’ll take a look at it

**Comment by robwebdev** [comment]
Sure, I'd definitely help out with testing.

**Comment by popeindustries** [comment]
https://github.com/popeindustries/lit-html-server/pull/8

**Comment by robwebdev** [comment]
@popeindustries I'm now using this on my experimental Hacker News app https://hackernews.robweb.dev / https://github.com/robwebdev/inclusive-hnpwa

It's working great 😎
