### ISSUE TITLE
Update docs to use {} for directives

### ISSUE THREAD

**Issue by lukasoppermann** [popeindustries/lit-html-server#98]
Hey @popeindustries,
awesome project, thank you very much.

I just noticed that the examples from the docs don't work for me. If I use:
```js
const repeat = require('@popeindustries/lit-html-server/directives/repeat.js');
```

I would actually have to use `repeat.repeat()` because it is exported as an object. To store the function from the js file to the const I need to import it as:
```js
const { repeat } = require('@popeindustries/lit-html-server/directives/repeat.js');
```

If this is not just the case for me, it would be awesome to update the examples. Thanks.

**Comment by popeindustries** [comment]
Oops! Yeah, that's a typo. Thanks for spotting that!
